### ISSUE TITLE
サーバー検索画面にて接続エラーが発生する

### ISSUE THREAD

**Issue by popkechupki** [popkechupki/transfer#6]
## 再現方法
1. /transfer でフォームを呼び出し
2. 一番上のサーバーリストボタンを選択
3. 接続エラーのアラートが出る

## 状況
- [x] 原因を特定
- [x] 修正

**Comment by popkechupki** [comment]
> java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 1007 path
> $.servers[0].categories

**Comment by popkechupki** [comment]
> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 1007 path $.servers[0].categories
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.google.gson.Gson.fromJson(Gson.java:848)
	at net.comorevi.np.transfer.network.ServerListLoader.getGsonEntry(ServerListLoader.java:63)
	at net.comorevi.np.transfer.network.ServerListLoader.getOnlineServers(ServerListLoader.java:19)
	at net.comorevi.np.transfer.form.FormManager.sendTransferListWindow(FormManager.java:54)
	at net.comorevi.np.transfer.form.FormManager.lambda$sendTransferHomeWindow$0(FormManager.java:37)
	at ru.nukkitx.events.EventListener.formResponded(EventListener.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:543)
	at cn.nukkit.Player.handleDataPacket(Player.java:2662)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:123)
	at cn.nukkit.network.Network.processInterfaces(Network.java:165)
	at cn.nukkit.Server.tick(Server.java:1164)
	at cn.nukkit.Server.tickProcessor(Server.java:940)
	at cn.nukkit.Server.start(Server.java:908)
	at cn.nukkit.Server.<init>(Server.java:589)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 1007 path $.servers[0].categories
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:380)
	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:368)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 29 more
